<?php require_once __DIR__ . "/../layout/head.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">
	<table class="table table-sm table-bordered table-hover">
		<thead class="table-dark">
			<tr>
				<th>2LD</th>
				<th>FQDN</th>
				<?php
				if ($active_modules ['whois'] === true) {
					?>
					<th>WhoIs</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['dns'] === true) {
					?>
					<th>DNS</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['ssl'] === true) {
					?>
					<th>SSL</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['http'] === true) {
					?>
					<th>HTTP</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['php'] === true) {
					?>
					<th>PHP</th>
					<?php
				}
				?>
			</tr>
		</thead>
		<tbody>
			<?php
			foreach ($websites as $parent => $group) {
				foreach ($group as $domain => $website) {
					?>
					<tr>
					<?php
					if (empty($currentParent) || $currentParent !== $parent) {
						?>
						<td rowspan="<?=count($group)?>" style="vertical-align: middle;">
							<a href="https://<?= $parent ?>/"><?= $parent ?></a>
						</td>
						<?php
					}
					?>
					<td class="<?= $website ["ispconfigInfos"] ['active']==='n' ? 'table-danger' : '' ?>">
						<a href="https://<?= $domain ?>/" target="_blank"><?= $domain ?></a>
					</td>
					<?php
					if ($website ["ispconfigInfos"] ['active'] === 'y') {
						if ($active_modules ['whois'] === true ) {
							if(!empty($website ['whoisInfos'])) {
								//TODO convert to use methods
								?>
								<td class="bg-<?= $website['whoisInfos']->getLabelType() ?>" title="<?= $website['whoisInfos']->getLabelTitle() ?>">
									<?= nl2br($website ['whoisInfos']->getLabelString()) ?>
								</td>
								<?php
							}
							else {
								?>
								<td>&nbsp;</td>
								<?php
							}
						}
						if ($active_modules ['dns'] === true) {
							if(!empty($website ['dnsInfos'])) {
								?>
								<td class="bg-<?= $website ['dnsInfos']->getLabelType() ?>" title="<?= $website['dnsInfos']->getLabelTitle() ?>">
									<?= nl2br($website ['dnsInfos']->getLabelString()) ?>
								</td>
								<?php
							}
							else {
								?>
								<td>&nbsp;</td>
								<?php
							}
						}
						if ($active_modules ['ssl'] === true) {
							if(!empty($website ['sslInfos'])) {
								?>
								<td class="bg-<?= $website ['sslInfos']->getLabelType() ?>" title="<?= $website['sslInfos']->getLabelTitle() ?>">
									<?= $website ['sslInfos']->getLabelString() ?>
								</td>
								<?php
							}
							else {
								?>
								<td>&nbsp;</td>
								<?php
							}
						}
						if ($active_modules ['http'] === true) {
							if(!empty($website ['httpInfos'])) {
								?>
								<td class="bg-<?= $website ['httpInfos']->getLabelType() ?>" title="<?= $website['httpInfos']->getLabelTitle() ?>">
									<?= $website ['httpInfos']->getLabelString() ?>
								</td>
								<?php
							}
							else {
								?>
								<td>&nbsp;</td>
								<?php
							}
						}
						if ($active_modules ['php'] === true) {
							if(!empty($website ['phpInfos'])) {
								?>
								<td class="bg-<?= $website ['phpInfos']->getLabelType() ?>" title="<?= $website['phpInfos']->getLabelTitle() ?>">
									<?= $website ['phpInfos']->getLabelString() ?>
								</td>
								<?php
							}
							else {
								?>
								<td>&nbsp;</td>
								<?php
							}
						}
					}
					else {
						?>
						<td colspan="5">&nbsp;</td>
						<?php
					}
					?>
				</tr>
				<?php
					$currentParent = $parent;
				}
			}
			?>
			</tbody>
			<thead class="table-dark">
				<tr>
					<th><?= $stats ["2LD_count"] ?></th>
					<th><?= $stats ["websites_count"] ?></th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
	</table>
	</main>

<?php require_once __DIR__ . "/../layout/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/foot.inc.phtml"; ?>
