<?php require_once __DIR__ . "/../layout/head.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/header.inc.phtml"; ?>

<?php require_once __DIR__ . "/check_modules.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">
	<table class="table table-sm table-bordered table-hover">
		<thead class="table-dark">
			<tr>
				<th>2LD</th>
				<th>FQDN</th>
				<?php
				if ($active_modules ['whois'] === true) {
					?>
					<th>WhoIs</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['dns'] === true) {
					?>
					<th>DNS</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['ssl'] === true) {
					?>
					<th>SSL</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['http'] === true) {
					?>
					<th>HTTP</th>
					<?php
				}
				?>
				<?php
				if ($active_modules ['php'] === true) {
					?>
					<th>PHP</th>
					<?php
				}
				?>
			</tr>
		</thead>
		<tbody>
			<?php
			foreach ($websites_grouped as $sld => $websites) {
				// calculate how many aliases & subdomains we will have for the whole 2LD
				$sld_subsites = 0;
				foreach ($websites as $website_id => $vhost) {
					$website_aliases = $aliases [$website_id] ?? [];
					$sld_subsites += count($website_aliases);
					$website_subdomains = $subdomains [$website_id] ?? [];
					$sld_subsites += count($website_subdomains);
				}
				
				foreach ($websites as $website_id => $vhost) {
					$vhost_subsites = count($aliases [$website_id] ?? []) + count($subdomains [$website_id] ?? []);
					?>
					<tr>
					<?php
					if (empty($currentSld) || $currentSld !== $sld) {
						?>
						<td rowspan="<?= count($websites) + $sld_subsites ?>" style="vertical-align: middle;">
							<a href="https://<?= $sld ?>/"><?= $sld ?></a>
						</td>
						<?php
					}
					?>
					<td class="<?= $vhost ['active'] === 'n' ? 'table-danger' : '' ?>">
						<a href="https://<?= $vhost ["domain"] ?>/" target="_blank"><?= $vhost ["domain"] ?></a>
					</td>
					
					<?php
					website_check_modules ($vhost, $active_modules, $vhost_subsites);
					?>
				</tr>
				
				<?php
				$website_aliases = $aliases [$website_id] ?? null;
				if(!empty($website_aliases)) {
					foreach ($website_aliases as $alias) {
						?>
						<tr>
							<td class="<?= $alias ['active'] === 'n' ? 'table-danger' : '' ?> ">
								<a class="ms-4" href="https://<?= $alias ["domain"] ?>/" target="_blank"><?= $alias ["domain"] ?></a>
							</td>
							<?php
							website_check_modules ($alias, $active_modules, -1);
							?>
						</tr>
						<?php
					}
				}
				?>
				
				<?php
				$website_subdomains = $subdomains [$website_id] ?? null;
				if(!empty($website_subdomains)) {
					foreach ($website_subdomains as $subdomain) {
						?>
						<tr>
							<td class="<?= $subdomain ['active'] === 'n' ? 'table-danger' : '' ?> ">
								<a class="ms-4" href="https://<?= $subdomain ["domain"] ?>/" target="_blank"><?= $subdomain ["domain"] ?></a>
							</td>
							<?php
							website_check_modules ($subdomain, $active_modules, -1);
							?>
						</tr>
						<?php
					}
				}
				?>
				
				<?php
				$currentSld = $sld;
				}
			}
			?>
			</tbody>
			<thead class="table-dark">
				<tr>
					<th><?= $stats ["2LD_count"] ?> 2LD</th>
					<th><?= $stats ["vhost_count"] ?> vhosts, <?= $stats ["aliases_count"] ?> aliases, <?= $stats ["subdomains_count"] ?> subdomains</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
	</table>
	</main>

<?php require_once __DIR__ . "/../layout/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/foot.inc.phtml"; ?>
