<?php require_once __DIR__ . "/../layout/head.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">
		<h2>Website : <?= $vhost ["domain"] ?></h2>
		
		<span <?= $vhost ["active"] === "y" ? "class='h3 bg-success' title='active'" : "class='h3 bg-danger' title='inactive'" ?>>id : <?= $vhost ["domain_id"] ?> </span> <br/>
		path ( <?= $vhost ["system_user"] ?> / <?= $vhost ["system_group"] ?> ) : <?= $vhost ["document_root"] ?> <br/>
		quota : <?= $vhost ["hd_quota"] === "-1" ? "unlimited" : ($vhost ["hd_quota"] . " MiB") ?> <br/>
		php : <?= !empty($vhost ["server_php_id"]) ? $vhost ["php"] : "none" ?> <?= $php_name ?> <br/>
		ssl : <?= $ssl ?> <br/>
		www sub-domain : <?= $vhost ["is_subdomainwww"] ? "yes" : "no" ?> <br/>
		stats : <?= $vhost ["stats_type"] ?> <br/>
		shell users 
		<?php
		if(count($shell_users) > 0) {
			?>
			( <?= $shell_users [0] ["puser"] ?? "" ?> / <?= $shell_users [0] ["pgroup"] ?? "" ?> ) : 
			<?= implode(", ", array_column($shell_users, "username")) ?> <br/>
			<?php
		}
		else {
			echo ": none";
		}
		?>
		<br/>
		
		<h3>backups : <?= $vhost ["backup_interval"] !== "none" ? $vhost ["backup_copies"] : "" ?> <?= $vhost ["backup_interval"] ?></h3>
		<?php
		if(count($backups_by_date) > 0) {
			?>
			<table class="table table-sm table-bordered">
				<thead>
					<tr>
						<th>date</th>
						<th>backups</th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach ($backups_by_date as $date_str => $days_backups) {
						$backups_strs = [];
						foreach ($days_backups as $backup) {
							$dt = DateTimeImmutable::createFromFormat("U", $backup ["tstamp"]);
							$backups_strs [] = "{$backup ["backup_type"]} ({$dt->format('H:i')})";
						}
						?>
						<tr>
							<td><?= $date_str ?></td>
							<td><?= implode(", ", $backups_strs) ?></td>
						</tr>
						<?php
					}
					?>
				</tbody>
				<tfoot>
					<tr>
						<th><?= count($backups_by_date) ?></th>
						<th><?= count($backups) ?></th>
					</tr>
				</tfoot>
			</table>
			<?php
		}
		else {
			echo "none <br/>";
		}
		?>
		<br/>
		
		TODO : <br/>
		- MysqL databases with users <br/>
		- list related aliases & subdomains <br/>
	</main>

<?php require_once __DIR__ . "/../layout/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/foot.inc.phtml"; ?>
