<?php require_once __DIR__ . "/../layout/head.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">
		<h2>Website : <?= $vhost ["domain"] ?></h2>
		
		id : <?= $vhost ["domain_id"] ?> <span <?= $vhost ["active"] === "y" ? "class='bg-success'>active" : "class='bg-danger'>inactive" ?></span> <br/>
		path : <?= $vhost ["document_root"] ?> ( <?= $vhost ["system_user"] ?> / <?= $vhost ["system_group"] ?> ) <br/>
		quota : <?= $vhost ["hd_quota"] === "-1" ? "unlimited" : ($vhost ["hd_quota"] . " Mo") ?> <br/>
		<br/>
		
		php : <?= !empty($vhost ["server_php_id"]) ? $vhost ["php"] : "none" ?> <?= $php_name ?> <br/>
		ssl : <?= $ssl ?> <br/>
		www sub-domain : <?= $vhost ["is_subdomainwww"] ? "yes" : "no" ?> <br/>
		<br/>
		
		stats : <?= $vhost ["stats_type"] ?> <br/>
		backups : <?= $vhost ["backup_interval"]!="none" ? $vhost ["backup_copies"] : "" ?> <?= $vhost ["backup_interval"] ?> <br/>
		<br/>
		
		shell users : 
		<?php
		if(count($shell_users) > 0) {
			?>
			( <?= $shell_users [0] ["puser"] ?? "" ?> / <?= $shell_users [0] ["pgroup"] ?? "" ?> ) <br/>
			<?= implode(", ", array_column($shell_users, "username")) ?> <br/>
			<?php
		}
		else {
			echo "none";
		}
		?>
		<br/>
		
		backups : 
		<?php
		
		if(count($backups) > 0) {
			?>
			<table class="table table-sm table-bordered">
				<thead>
					<tr>
						<th>type</th>
						<th>date</th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach ($backups as $backup) {
						$date = DateTimeImmutable::createFromFormat("U", $backup ["tstamp"]);
						?>
						<tr>
							<td><?= $backup ["backup_type"] ?></td>
							<td><?= $date->format("c") ?></td>
						</tr>
						<?php
					}
					?>
				</tbody>
				<tfoot>
					<tr>
						<th>#</th>
						<th><?= count($backups) ?></th>
					</tr>
				</tfoot>
			</table>
			<?php
		}
		else {
			echo "none <br/>";
		}
		?>
		<br/>
		
		TODO : <br/>
		- MysqL databases with users <br/>
		- list related aliases & subdomains <br/>
	</main>

<?php require_once __DIR__ . "/../layout/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/foot.inc.phtml"; ?>
