<?php require_once __DIR__ . "/../layout/head.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container-fluid">
		<h2>Websites list (<?= count($vhosts) ?>)</h2>
	<table class="table table-sm table-bordered table-hover">
		<thead class="table-dark">
			<tr>
				<th>id</th>
				<th>FQDN</th>
				<th>serveur</th>
			</tr>
		</thead>
		<tbody>
			<?php
			foreach ($vhosts as $vhost) {
				$server_config = $servers_configs [$vhost ["server_id"]] ?? null;
				$hostname = $server_config ["server"] ["hostname"] ?? "";
				$shell_users_str = implode(PHP_EOL, array_column($shell_users [$vhost ["domain_id"]] ?? [], "username"));
				?>
				<tr>
					<td>
						<a href="<?= $BASE . $f3->alias("websiteDetail", ["id" => $vhost ["domain_id"]]) ?>" title="voir le détail">
							<?= $vhost ["domain_id"] ?>
						</a>
					</td>
					<td class="<?= $vhost ["active"] === "n" ? "table-danger" : "" ?>">
						<a href="http://<?=$vhost ["domain"]?>" target="_blank" title="ouvrir le site web dans un onglet">
							<?= $vhost ["domain"] ?>
						</a>
					</td>
					<td><?= $hostname ?></td>
				</tr>
				<?php
			}
			?>
			</tbody>
			<thead class="table-dark">
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
	</table>
	</main>

<?php require_once __DIR__ . "/../layout/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/../layout/foot.inc.phtml"; ?>
