<?php require_once __DIR__ . "/head.inc.phtml"; ?>

<body>
<?php require_once __DIR__ . "/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container">
	<table class="table table-sm table-bordered ">
		<thead class="thead-dark">
			<tr>
				<th>2LD</th>
				<th>FQDN</th>
			</tr>
		</thead>
		<tbody class="table-hover">
		</tbody>
		<thead class="thead-dark">
			<tr>
				
			</tr>
		</thead>
	</table>
	</main>

<?php require_once __DIR__ . "/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/foot.inc.phtml"; ?>
