<?php require_once __DIR__ . "/head.inc.phtml"; ?>

<body>
<?php require_once __DIR__ . "/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container">
		<table class="table table-sm table-bordered table-hover">
			<thead class="table-dark">
				<tr>
					<th> <input type="checkbox" id="all_domain_entries" name="all_domain_entries"> </th>
					<th> domain </th>
					<th> type </th>
					<th> name </th>
					<th> data </th>
					<th> actions </th>
				</tr>
			</thead>
			<thead class="table-secondary">
				<tr>
					<form action="" method="get">
						<th> <i class="fas fa-filter"></i> </th>
						<th> <input type="text" class="w-100" id="domain" name="domain" value="<?= $GET["domain"] ?? "" ?>" placeholder="domain">  </th>
						<th> <input type="text" class="w-100" id="type" name="type" value="<?= $GET["type"] ?? "" ?>" placeholder="type"> </th>
						<th> <input type="text" class="w-100" id="name" name="name" value="<?= $GET["name"] ?? "" ?>" placeholder="name"> </th>
						<th> <input type="text" class="w-100" id="data" name="data" value="<?= $GET["data"] ?? "" ?>" placeholder="data"> </th>
						<th> &nbsp; <input type="submit" class="d-none" /> </th>
					</form>
				</tr>
			</thead>
			<form action="<?= $BASE ?>/domains/bulk_edit" method="post">
				<tbody class="">
				<?php
				foreach($domain_entries as $domain_entry) {
					?>
					<tr>
						<td> <input type="checkbox" id="domain_entry[<?= $domain_entry["id"]?>]" name="domain_entry[<?= $domain_entry["id"]?>]" data-id = "<?= $domain_entry["id"]?>"> </td>
						<td><?= $domain_entry["domain"]?></td>
						<td><?= $domain_entry["type"]?></td>
						<td><?= $domain_entry["name"]?></td>
						<td class="truncate"><?= $domain_entry["data"]?></td>
						<td> &nbsp; </td>
					</tr>
					<?php
				}
				?>
				</tbody>
				<thead class="table-secondary">
						<th> <span id="selected-count"> 0 </span> </th>
						<th> FILTERED : <?= $stats ["nb"] ?> </th>
						<th> TOTAL : <?= $stats ["total"] ?> </th>
						<th> &nbsp; </th>
						<th>
							<input type="text" id="" class="" name="data" value="" placeholder="data">
							<button id="bulk_edit_data" class="btn btn-primary">modifier</button>
						</th>
						<th> actions </th>
				</thead>
				</form>
		</table>
	</main>

<?php require_once __DIR__ . "/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/foot.inc.phtml"; ?>
