<?php require_once __DIR__ . "/head.inc.phtml"; ?>

<body>
<?php require_once __DIR__ . "/header.inc.phtml"; ?>

	<!-- Begin page content -->
	<main role="main" class="container">
	
		<h1> bulk mailbox creation </h1>
		
		<p>
			Delete mailbox if asked. <br/>
			Then create the mailbox with the specified quota. <br/>
			Default backup is 2x monthly.
		</p>
		<p>
			Maildomain has to exist (create manually if needed). <br/>
			Mailboxes will be attached according to maildomain, with same server and client.
		</p>
		
		<form action="" method="post" enctype="multipart/form-data">
			<div class="form-group form-check">
				<input class="form-check-input" type="checkbox" id="drop" name="drop">
				<label clas="form-check-label" for="drop"> drop mailbox if exists </label>
			</div>
			
			<div class="form-group">
				<label for="file"> select a CSV file with (email + password) rows </label>
				<input type="file" id="file" name="file" required>
			</div>
			
			<div class="form-group">
				<label for="quota"> quota (GB) </label>
				<input type="number" id="quota" name="quota" value="10" required>
			</div>
			<button type="submit" class="btn btn-primary"> Send </button>
		</form>

	</main>

<?php require_once __DIR__ . "/footer.inc.phtml"; ?>

<?php require_once __DIR__ . "/foot.inc.phtml"; ?>
