	<footer class="footer">
		<div class="container">
			<span class="text-muted"><a href="https://www.github.com/olaulau/IspAdmin">IspAdmin</a> (c) <a href="https://www.github.com/olaulau">olaulau</a></span>
		</div>
	</footer>
	

	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				<a href="https://www.github.com/olaulau/IspAdmin">IspAdmin</a> (c) <a href="https://www.github.com/olaulau">olaulau</a> - <?= htmlspecialchars_decode($footer_additional_text ?? "") ?>
			</span>
		</div>
	</footer>