<!doctype html>
<html lang="fr">
<head>
<link rel="icon" href="data:;base64,iVBORw0KGgo=">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Websites</title>

<!-- Bootstrap core CSS -->
<link href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/sticky-footer-navbar.css" rel="stylesheet">
</head>

<body>

	<header>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<a class="navbar-brand" href="<?= $BASE ?>/">IspAdmin</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
				aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active"><a class="nav-link" href="#"> Websites <span class="sr-only">(current)</span></a></li>
				</ul>
			</div>
		</nav>
	</header>

	<!-- Begin page content -->
	<main role="main" class="container">
	<table class="table table-sm table-bordered ">
		<thead class="thead-dark">
			<tr>
				<th>Domain</th>
				<?php
				if ($active_modules['whois'] === true) {///////////////////////////
					?>
					<th>WhoIs</th>
					<?php
				}
				?>
				<?php
				if ($active_modules['dns'] === true) {
					?>
					<th>DNS</th>
					<?php
				}
				?>
				<?php
				if ($active_modules['ssl'] === true) {
					?>
					<th>SSL</th>
					<?php
				}
				?>
				<?php
				if ($active_modules['http'] === true) {
					?>
					<th>HTTP</th>
					<?php
				}
				?>
				<?php
				if ($active_modules['php'] === true) {
					?>
					<th>PHP</th>
					<?php
				}
				?>
			</tr>
		</thead>
		<tbody class="table-hover">
			<?php
			foreach ($websites as $domain => $website) {
				?>
				<tr>
				<td class="<?= $website["ispconfigInfos"]['active']==='n' ? 'table-danger' : '' ?>">
					<a href="https://<?= $domain ?>/"><?= $domain ?></a>
				</td>
				<?php
				if ($active_modules['whois'] === true ) {
					?>
					<td class="table-<?= $website['whoisInfos']['labelType'] ?>"><?= nl2br($website['whoisInfos']['labelString']) ?></td>
					<?php
				}
				?>
				<?php
				if ($active_modules['dns'] === true) {
					?>
					<td class="table-<?= $website['dnsInfos']->getLabelType() ?>"><?= nl2br($website['dnsInfos']->getLabelString()) ?></td>
					<?php
				}
				?>
				<?php
				if ($active_modules['ssl'] === true) {
					?>
					<td class="table-<?= $website['sslInfos']->getLabelType() ?>"><?= $website['sslInfos']->getLabelString() ?></td>
					<?php
				}
				?>
				<?php
				if ($active_modules['http'] === true) {
					?>
					<td class="table-<?= $website['httpInfos']->getLabelType() ?>"><?= $website['httpInfos']->getLabelString() ?></td>
					<?php
				}
				?>
				<?php
				if ($active_modules['php'] === true) {
					?>
					<td class="<?= !empty($website['phpInfos']['label_type']) ? 'table-'.$website['phpInfos']['label_type'] : '' ?>"> <?= $website['phpInfos']['label_string'] ?> </td>
					<?php
				}
				?>
				
			</tr>
			<?php
			}
			?>
			</tbody>
	</table>
	</main>

	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				<a href="https://www.github.com/olaulau/IspAdmin">IspAdmin</a> (c) <a href="https://www.github.com/olaulau">olaulau</a> - 
				<?= $stats['executed_cmds'] ?> / <?= $stats['total_cmds'] ?> executed - 
				generated in <?= $generation_time ?> ms
			</span>
		</div>
	</footer>

	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="vendor/components/jquery/jquery.min.js"></script>
	<script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>
