	<footer class="footer">
		<div class="container">
			<span class="text-muted"><a href="https://www.github.com/olaulau/IspAdmin">IspAdmin</a> (c) <a href="https://www.github.com/olaulau">olaulau</a></span>
		</div>
	</footer>
	

	<footer class="footer">
		<div class="container">
			<span class="text-muted">
				<a class="text-decoration-none" href="https://www.github.com/olaulau/IspAdmin"><i class="fa-brands fa-github"></i> github</a> 
				|
				<a class="text-decoration-none" href="https://www.github.com/olaulau/"><img style="max-height: 1rem;" src="https://avatars.githubusercontent.com/u/1771905"/> olaulau</a> 
				|
				<a class="text-decoration-none" href="https://www.github.com/olaulau/IspAdmin"><i class="fa-solid fa-hammer"></i> IspAdmin</a> 
				<?= htmlspecialchars_decode($footer_additional_text ?? "") ?>
			</span>
		</div>
	</footer>