	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="<?= $BASE ?>/vendor/components/jquery/jquery.min.js"></script>
	<script src="<?= $BASE ?>/vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	
	<script src="<?= $BASE ?>/assets/<?= $PAGE["name"] ?>.js"></script>
</body>
</html>