	<header>
		<!-- Fixed navbar -->
		<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
			<div class="container-fluid">
				<a class="navbar-brand" href="<?= $BASE ?>/"><i class="fa-solid fa-hammer"></i> ISPconfig Admin</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
					aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item"> <a class="nav-link <?= $PAGE["name"] === "websites" ? "active" : "" ?>" href="<?= $BASE ?>/websites"> <i class="fa-solid fa-globe"></i> WebSites </a> </li>
						<li class="nav-item"> <a class="nav-link <?= $PAGE["name"] === "emails" ? "active" : "" ?>" href="<?= $BASE ?>/emails"> <i class="fa-solid fa-envelope"></i> E-mails </a> </li>
						<li class="nav-item"> <a class="nav-link <?= $PAGE["name"] === "domains" ? "active" : "" ?>" href="<?= $BASE ?>/domains"> <i class="fa-solid fa-address-book"></i> DNS </a> </li>
					</ul>
				</div>
				<ul class="navbar-nav px-3">
					<li class="nav-item text-nowrap"> <span class="nav-link"><?= $SESSION["auth_user"] ?> <a href="<?=$BASE?>/logout" class="text-decoration-none text-danger" href="#"> <i class="fa-solid fa-right-from-bracket" title="déconnecter"></i> </a> </span> </li>
				</ul>
			</div>
		</nav>
	</header>